name: CI Tests

on:
  push:
    branches:
      - main
      - 'dev/**'
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Start services
        run: docker compose up -d postgres redis

      - name: Apply Prisma migrations
        run: pnpm prisma migrate deploy --schema prisma/schema.prisma

      - name: Run integration tests
        run: pnpm test:integration

      - name: Teardown services
        if: always()
        run: docker compose down --remove-orphans
